### ISSUE TITLE
semantic classes or an id for the questions and answers table

### ISSUE THREAD

**Issue by matthewford** [alphagov/digitalmarketplace-supplier-frontend#599]
Hello,

As there is no notification system or email when an answer to a question is posted, I would like to scrape the page, to make this easier can semantic classes be used or an id for the Q&A table to differentiate it from the table above.

**Comment by tombye** [comment]
Hi Matt, we tend to use xpath for this kind of thing in our integration tests as the tables can be identified by their preceding heading (which has an id).

For example:

`//h2[@id="clarification-questions"]/following-sibling::table/tbody/tr/td[contains(@class, "summary-item-field")]/span/text()`

...will return an array of all the Q&A text.
